Web Development/Django app/Auto_Email/Auto_Email/urls.py
from django.contrib import admin
from django.urls import path, include
from. import views
urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('thanks/',views.Thanks.as_view(), name='thanks'),
    path('admin/', admin.site.urls),
    path('success/',views.Success.as_view(), name='success'),
    path('accounts/', include('accounts.urls')),
    path('auto_mail/', include('auto_mail.urls')),
]

Web Development/Django app/Auto_Email/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('sign_up/',views.SignUpView.as_view(), name='sign_up'),
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

Web Development/Django app/Auto_Email/auto_mail/urls.py
from django.urls import path
from . import views
app_name = 'auto_mail'

urlpatterns = [
    path('create/',views.MailCreationView.as_view(), name='create'),
    path('list/',views.MailListView.as_view(), name='list'),
    path('mail/<int:pk>/', views.MailDetailView.as_view(), name='detail'),
    path('mail/<int:pk>/post/', views.post, name='post'),
]

Web Development/Django app/Auto_Email/accounts/models.py
from django.db import models
from django.contrib.auth import models
# Create your models here.


class User(models.User,models.PermissionsMixin):
    def __str__(self):
        return f'@{self.username}'
    

Web Development/Django app/Auto_Email/auto_mail/models.py
from django.db import models

# Create your models here.

class Mail(models.Model):
    created_on = models.DateField(auto_now=True)
    subject = models.CharField(max_length = 100)
    message = models.TextField()

    def __str__(self):
        return self.created_on
        

Web Development/Django app/Auto_Email/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserSignUpForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

Web Development/Django app/Auto_Email/auto_mail/forms.py
from django import forms
from . import models

class MailCreationForm(forms.ModelForm):
    class Meta:
        model = models.Mail
        fields = ('subject','message')

Web Development/Django app/Auto_Email/Auto_Email/views.py
from django.views import generic


class Thanks(generic.TemplateView):
    template_name = 'thanks.html'

class Index(generic.TemplateView):
    template_name = 'index.html'

class Success(generic.TemplateView):
    template_name = 'success.html'

Web Development/Django app/Auto_Email/accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from . import forms
# Create your views here.


class SignUpView(generic.CreateView):  
    form_class = forms.UserSignUpForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/sign_up.html'

Web Development/Django app/Auto_Email/auto_mail/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from . import models
from . import forms
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
# Create your views here.

User = get_user_model()

class MailCreationView(generic.CreateView,LoginRequiredMixin):
    login_url = '/login/'
    template_name = 'auto_mail/mail.html'
    model = models.Mail
    form_class = forms.MailCreationForm

    def get_success_url(self):
        return reverse('auto_mail:detail',kwargs={'pk':self.object.pk})

class MailListView(generic.ListView,LoginRequiredMixin):
    login_url = '/login/'
    template_name = 'auto_mail/mail_list.html'
    context_object_name = 'mail_list_content'

    def get_queryset(self):
        return models.Mail.objects.filter(created_on__lte=timezone.now()).order_by('-created_on')

class MailDetailView(LoginRequiredMixin,generic.DetailView):
    login_url = '/login/'
    template_name = 'auto_mail/mail_detail.html'
    model = models.Mail

@login_required
def post(request,pk):
    # mail = get_object_or_404(models.Mail,pk=pk)
    Subject = models.Mail.objects.get(pk=pk).subject
    Message = models.Mail.objects.get(pk=pk).message
    emails = User.objects.filter(is_active=True).values_list('email', flat=True)
    send_mail(Subject,Message,'djangospare@gmail.com',emails,fail_silently=False)

    return redirect('success')

Web Development/Django app/Auto_Email/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body_block %}

    <div class='container login'>
        <h2>SignUp here!</h2>
        <form method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class='btn btn-primary' type='Submit' value='Login' >
        <form>
    <div>

{% endblock body_block %}

Web Development/Django app/Auto_Email/accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body_block %}

    <div class='container sign-up'>
        
        <form method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type='Submit' class='btn btn-primary' value='Sign Up'>
        </form>
    
    </div>

{% endblock body_block %}

Web Development/Django app/Auto_Email/auto_mail/templates/auto_mail/mail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body_block %}

    <div class='container mail'>
        <form method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type='Submit' class='btn btn-primary' value='Done'>
        </form>
    </div>

{% endblock body_block %}

Web Development/Django app/Auto_Email/auto_mail/templates/auto_mail/mail_detail.html
{% extends 'base.html' %}

{% block body_block %}
    <div class='container detail'>
        <h1>Created on: {{mail.created_on}}</h1>

        <h3>Subject: {{mail.subject}}</h3>

        <h3>Message: {{mail.message}}</h3>

        <a class='btn btn-danger' href="{% url 'auto_mail:post' pk=mail.pk %}">Mail</a>
    </div>
{% endblock body_block %}

Web Development/Django app/Auto_Email/auto_mail/templates/auto_mail/mail_list.html
{% extends 'base.html' %}

{% block body_block %}

    <div class='container list'>
        {% for mail in mail_list_content %}
            <h4>
                <a href="{% url 'auto_mail:detail' pk=mail.pk %}">{{mail.created_on}}</a>
            </h4>
        {% endfor %}
    </div>

{% endblock body_block %}

Web Development/Django app/Auto_Email/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AUTO EMAIL</title>
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">AUTO MAIL</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'auto_mail:list' %}">Mail List</a>
            </li>
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'auto_mail:create' %}" >Create Mail</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'accounts:logout' %}">LogOut</a>        
            {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}">LogIn</a>
                <a class="nav-link" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            {% endif %}
          </form>
        </div>
    </nav>
        
    <div class='container'>

        {% block body_block %}

        {% endblock body_block %}    
    
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
</html>

Web Development/Django app/Auto_Email/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
    <div class='container'>

        <h1>Welcome to AUTO MAIL</h1>

    </div>
{% endblock body_block %}

Web Development/Django app/Auto_Email/templates/success.html
{% extends 'base.html' %}
{% block body_block %}

<div class='container success'>
    <h3>Mail has been successfully sent!</h3>
</div>

{% endblock body_block %}

Web Development/Django app/Auto_Email/templates/thanks.html
{% extends 'base.html' %}
{% block body_block %}

    <div class='container thanks'>
        <h3>Thanks for logging in!,Come back soon!</h3>
    </div>

{% endblock body_block %}